services:
  - type: web
    name: mt-summarizer
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
